### ISSUE TITLE
Unified list of open datasets by government body

### ISSUE THREAD

**Issue by anuveyatsu** [open-data-kazakhstan/ideas#4]
Original title: Единый перечень открытых данных государственных органов, размещаемых на интернет-портале открытых данных.

Source: https://adilet.zan.kz/rus/docs/P2100000774

## Tasks

* [x] Specify list of columns in a processed data
* [ ] Create a script using dataflows library to parse, transform and load data
* [ ] Make sure metadata (`datapackage.json`) is there (it should be auto-generated by dataflows library)
* [ ] Create docs (README.md)
* [ ] Setup data pipelines and run quarterly (why quarterly? because we don't know how often the source updates - we assume it is irregular, e.g., once in 1-2 years but we'd like to pick up updates sooner than later... running the data pipelines once in quarter is inexpensive ...) 

## Analysis

The data table looks like this:

<img width="919" alt="Screen Shot 2022-03-28 at 7 34 57 PM" src="https://user-images.githubusercontent.com/17809581/160409547-e5480bd7-33c9-4697-87be-b6dfdce28ae8.png">

We want to get normalized version of this data:

* Columns 1 and 2 are just enumeration so we don't need it.
* We need columns 3-7 and we want to add a new column "Категория" where we can have relevant cateogry, e.g., "Государственный сектор" (see the screenshot above).

This is how the resulting csv data would look like:

[sample.csv](https://github.com/open-data-kazakhstan/ideas/files/8363268/sample.csv)
